server
{
	listen 8080 default;
	charset utf-8;

	root URIs;
	index index.html;
	auto_index on;
	upload_folder ./uploads;
	client_max_body_size 8192;
	allowed_methods  GET;

	location /tests
	{
		auto_index on;
		cgi .py /usr/bin/python3;
		cgi .sh /bin/bash;
		cgi .php /bin/php8.1;
		allowed_methods  GET POST;
	}

	location /uploads
	{
		auto_index off;
		index index.html;
		file_upload on;
		allowed_methods  GET POST DELETE;
	}
}